id: P000322
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG23697
  title: རྟེན་འབྲེལ་ཟབ་མོའི་བརྗོད་བྱ་སྣ་ཚོགས་པ་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་སྐལ་ལྡན་ཡིད་འཕྲོག
  author: ''
  volumes:
    e9c4d1305c3b4171bb7d8003a5458f3e:
      image_group_id: I1KG23780
      title: Volume 1 of rten 'brel zab mo'i brjod bya sna tshogs pa phyogs gcig tu
        bsdebs pa skal ldan yid 'phrog
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
